#!/usr/bin/env python3
"""One-shot generator for wordbank drip batches. Run from repo root."""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path("backend/content/wordbank")
EXISTING = {
    (w["lemma"], w.get("article") or "")
    for w in json.loads((OUT / "a1-batch-01.json").read_text(encoding="utf-8"))
}

# lemma, article, plural, translation, pos, cefr, topic, exampleDe, exampleEn,
# examplePluralDe?, examplePluralEn?, usageNote?
RAW: list[tuple] = [
    # --- FOOD_DRINK ---
    ("Käse", "der", "Käse", "cheese", "NOUN", "A1", "FOOD_DRINK", "Ich esse gern Käse.", "I like eating cheese.", None, None, None),
    ("Butter", "die", None, "butter", "NOUN", "A1", "FOOD_DRINK", "Die Butter ist im Kühlschrank.", "The butter is in the fridge.", None, None, "Usually uncountable; no plural in everyday use."),
    ("Ei", "das", "Eier", "egg", "NOUN", "A1", "FOOD_DRINK", "Zum Frühstück esse ich ein Ei.", "I eat an egg for breakfast.", "Die Eier sind frisch.", "The eggs are fresh.", None),
    ("Fleisch", "das", None, "meat", "NOUN", "A1", "FOOD_DRINK", "Wir kaufen Fleisch auf dem Markt.", "We buy meat at the market.", None, None, None),
    ("Fisch", "der", "Fische", "fish", "NOUN", "A1", "FOOD_DRINK", "Heute gibt es Fisch.", "Today there is fish.", None, None, None),
    ("Gemüse", "das", None, "vegetables", "NOUN", "A1", "FOOD_DRINK", "Gemüse ist gesund.", "Vegetables are healthy.", None, None, "Collective noun; often no plural."),
    ("Obst", "das", None, "fruit", "NOUN", "A1", "FOOD_DRINK", "Obst liegt auf dem Tisch.", "Fruit is on the table.", None, None, None),
    ("Banane", "die", "Bananen", "banana", "NOUN", "A1", "FOOD_DRINK", "Die Banane ist gelb.", "The banana is yellow.", "Die Bananen sind reif.", "The bananas are ripe.", None),
    ("Orange", "die", "Orangen", "orange", "NOUN", "A1", "FOOD_DRINK", "Ich trinke Orangensaft.", "I drink orange juice.", "Die Orangen schmecken süß.", "The oranges taste sweet.", None),
    ("Tomate", "die", "Tomaten", "tomato", "NOUN", "A1", "FOOD_DRINK", "Die Tomate ist rot.", "The tomato is red.", "Die Tomaten sind frisch.", "The tomatoes are fresh.", None),
    ("Kartoffel", "die", "Kartoffeln", "potato", "NOUN", "A1", "FOOD_DRINK", "Wir kochen Kartoffeln.", "We cook potatoes.", "Die Kartoffeln sind heiß.", "The potatoes are hot.", None),
    ("Reis", "der", None, "rice", "NOUN", "A1", "FOOD_DRINK", "Zum Abendessen gibt es Reis.", "There is rice for dinner.", None, None, None),
    ("Nudeln", "die", "Nudeln", "pasta / noodles", "NOUN", "A1", "FOOD_DRINK", "Die Nudeln sind fertig.", "The pasta is ready.", None, None, "Usually plural in German."),
    ("Suppe", "die", "Suppen", "soup", "NOUN", "A1", "FOOD_DRINK", "Die Suppe ist heiß.", "The soup is hot.", None, None, None),
    ("Salat", "der", "Salate", "salad", "NOUN", "A1", "FOOD_DRINK", "Ich esse einen Salat.", "I eat a salad.", None, None, None),
    ("Zucker", "der", None, "sugar", "NOUN", "A1", "FOOD_DRINK", "Der Kaffee braucht Zucker.", "The coffee needs sugar.", None, None, None),
    ("Salz", "das", None, "salt", "NOUN", "A1", "FOOD_DRINK", "Das Salz steht auf dem Tisch.", "The salt is on the table.", None, None, None),
    ("Pfeffer", "der", None, "pepper (spice)", "NOUN", "A1", "FOOD_DRINK", "Ich nehme etwas Pfeffer.", "I'll take some pepper.", None, None, None),
    ("Öl", "das", None, "oil", "NOUN", "A1", "FOOD_DRINK", "Wir kochen mit Öl.", "We cook with oil.", None, None, None),
    ("Saft", "der", "Säfte", "juice", "NOUN", "A1", "FOOD_DRINK", "Ich trinke Apfelsaft.", "I drink apple juice.", "Die Säfte sind kalt.", "The juices are cold.", None),
    ("Bier", "das", "Biere", "beer", "NOUN", "A1", "FOOD_DRINK", "Er trinkt ein Bier.", "He drinks a beer.", None, None, None),
    ("Wein", "der", "Weine", "wine", "NOUN", "A1", "FOOD_DRINK", "Wir trinken Wein zum Essen.", "We drink wine with the meal.", None, None, None),
    ("Frühstück", "das", "Frühstücke", "breakfast", "NOUN", "A1", "FOOD_DRINK", "Das Frühstück ist um acht Uhr.", "Breakfast is at eight o'clock.", None, None, None),
    ("Mittagessen", "das", "Mittagessen", "lunch", "NOUN", "A1", "FOOD_DRINK", "Das Mittagessen war lecker.", "Lunch was delicious.", None, None, None),
    ("Abendessen", "das", "Abendessen", "dinner", "NOUN", "A1", "FOOD_DRINK", "Zum Abendessen essen wir Pizza.", "We eat pizza for dinner.", None, None, None),
    ("Restaurant", "das", "Restaurants", "restaurant", "NOUN", "A1", "FOOD_DRINK", "Wir gehen in ein Restaurant.", "We are going to a restaurant.", None, None, None),
    ("Kühlschrank", "der", "Kühlschränke", "fridge", "NOUN", "A1", "HOME", "Die Milch ist im Kühlschrank.", "The milk is in the fridge.", None, None, None),
    ("Teller", "der", "Teller", "plate", "NOUN", "A1", "FOOD_DRINK", "Der Teller ist leer.", "The plate is empty.", "Die Teller sind sauber.", "The plates are clean.", None),
    ("Glas", "das", "Gläser", "glass", "NOUN", "A1", "FOOD_DRINK", "Ich trinke ein Glas Wasser.", "I drink a glass of water.", "Die Gläser stehen dort.", "The glasses are over there.", None),
    ("Tasse", "die", "Tassen", "cup", "NOUN", "A1", "FOOD_DRINK", "Eine Tasse Tee, bitte.", "A cup of tea, please.", "Die Tassen sind heiß.", "The cups are hot.", None),
    ("Messer", "das", "Messer", "knife", "NOUN", "A1", "FOOD_DRINK", "Das Messer ist scharf.", "The knife is sharp.", None, None, None),
    ("Gabel", "die", "Gabeln", "fork", "NOUN", "A1", "FOOD_DRINK", "Wo ist die Gabel?", "Where is the fork?", "Die Gabeln liegen hier.", "The forks are here.", None),
    ("Löffel", "der", "Löffel", "spoon", "NOUN", "A1", "FOOD_DRINK", "Ich brauche einen Löffel.", "I need a spoon.", None, None, None),
    ("Hunger", "der", None, "hunger", "NOUN", "A1", "FOOD_DRINK", "Ich habe Hunger.", "I am hungry.", None, None, "Use: Hunger haben."),
    ("Durst", "der", None, "thirst", "NOUN", "A1", "FOOD_DRINK", "Hast du Durst?", "Are you thirsty?", None, None, "Use: Durst haben."),
    ("lecker", None, None, "delicious / tasty", "ADJECTIVE", "A1", "FOOD_DRINK", "Das Essen ist lecker.", "The food is delicious.", None, None, None),
    ("kochen", None, None, "to cook", "VERB", "A1", "FOOD_DRINK", "Ich koche heute Abend.", "I am cooking this evening.", None, None, None),
    ("bestellen", None, None, "to order", "VERB", "A1", "FOOD_DRINK", "Wir bestellen Pizza.", "We order pizza.", None, None, None),
    ("schmecken", None, None, "to taste / be tasty", "VERB", "A1", "FOOD_DRINK", "Das schmeckt gut.", "That tastes good.", None, None, None),
    # --- HOME ---
    ("Wohnung", "die", "Wohnungen", "apartment", "NOUN", "A1", "HOME", "Meine Wohnung ist klein.", "My apartment is small.", "Die Wohnungen sind neu.", "The apartments are new.", None),
    ("Wohnzimmer", "das", "Wohnzimmer", "living room", "NOUN", "A1", "HOME", "Wir sitzen im Wohnzimmer.", "We sit in the living room.", None, None, None),
    ("Schlafzimmer", "das", "Schlafzimmer", "bedroom", "NOUN", "A1", "HOME", "Das Schlafzimmer ist ruhig.", "The bedroom is quiet.", None, None, None),
    ("Badzimmer", "das", "Badzimmer", "bathroom", "NOUN", "A1", "HOME", "Das Badzimmer ist frei.", "The bathroom is free.", None, None, "Also: das Bad."),
    ("Boden", "der", "Böden", "floor / ground", "NOUN", "A1", "HOME", "Der Boden ist sauber.", "The floor is clean.", None, None, None),
    ("Wand", "die", "Wände", "wall", "NOUN", "A1", "HOME", "Das Bild hängt an der Wand.", "The picture hangs on the wall.", None, None, None),
    ("Decke", "die", "Decken", "ceiling / blanket", "NOUN", "A1", "HOME", "Die Decke ist weiß.", "The ceiling is white.", None, None, "Also means blanket."),
    ("Lampe", "die", "Lampen", "lamp", "NOUN", "A1", "HOME", "Die Lampe ist an.", "The lamp is on.", "Die Lampen sind hell.", "The lamps are bright.", None),
    ("Sofa", "das", "Sofas", "sofa", "NOUN", "A1", "HOME", "Ich sitze auf dem Sofa.", "I sit on the sofa.", None, None, None),
    ("Schrank", "der", "Schränke", "cupboard / wardrobe", "NOUN", "A1", "HOME", "Die Bücher sind im Schrank.", "The books are in the cupboard.", None, None, None),
    ("Regal", "das", "Regale", "shelf", "NOUN", "A1", "HOME", "Das Regal ist voll.", "The shelf is full.", None, None, None),
    ("Schlüssel", "der", "Schlüssel", "key", "NOUN", "A1", "HOME", "Wo ist der Schlüssel?", "Where is the key?", "Die Schlüssel liegen hier.", "The keys are here.", None),
    ("Licht", "das", "Lichter", "light", "NOUN", "A1", "HOME", "Bitte mach das Licht an.", "Please turn on the light.", None, None, None),
    ("Heizung", "die", "Heizungen", "heating", "NOUN", "A1", "HOME", "Die Heizung ist kaputt.", "The heating is broken.", None, None, None),
    ("Garten", "der", "Gärten", "garden", "NOUN", "A1", "HOME", "Die Kinder spielen im Garten.", "The children play in the garden.", None, None, None),
    ("Balkon", "der", "Balkone", "balcony", "NOUN", "A1", "HOME", "Wir sitzen auf dem Balkon.", "We sit on the balcony.", None, None, None),
    ("Nachbar", "der", "Nachbarn", "neighbor (m.)", "NOUN", "A1", "HOME", "Mein Nachbar ist freundlich.", "My neighbor is friendly.", "Die Nachbarn sind nett.", "The neighbors are nice.", None),
    ("Nachbarin", "die", "Nachbarinnen", "neighbor (f.)", "NOUN", "A1", "HOME", "Die Nachbarin wohnt nebenan.", "The neighbor lives next door.", None, None, None),
    ("sauber", None, None, "clean", "ADJECTIVE", "A1", "HOME", "Die Küche ist sauber.", "The kitchen is clean.", None, None, None),
    ("schmutzig", None, None, "dirty", "ADJECTIVE", "A1", "HOME", "Das Fenster ist schmutzig.", "The window is dirty.", None, None, None),
    ("öffnen", None, None, "to open", "VERB", "A1", "HOME", "Bitte öffne die Tür.", "Please open the door.", None, None, None),
    ("schließen", None, None, "to close", "VERB", "A1", "HOME", "Schließ das Fenster!", "Close the window!", None, None, None),
    ("putzen", None, None, "to clean", "VERB", "A1", "HOME", "Ich putze die Wohnung.", "I clean the apartment.", None, None, None),
    # --- TRAVEL ---
    ("Fahrrad", "das", "Fahrräder", "bicycle", "NOUN", "A1", "TRAVEL", "Ich fahre mit dem Fahrrad.", "I ride a bicycle.", "Die Fahrräder stehen draußen.", "The bicycles are outside.", None),
    ("Taxi", "das", "Taxis", "taxi", "NOUN", "A1", "TRAVEL", "Wir nehmen ein Taxi.", "We take a taxi.", None, None, None),
    ("U-Bahn", "die", "U-Bahnen", "subway / metro", "NOUN", "A1", "TRAVEL", "Die U-Bahn ist schnell.", "The subway is fast.", None, None, None),
    ("Straßenbahn", "die", "Straßenbahnen", "tram", "NOUN", "A1", "TRAVEL", "Die Straßenbahn kommt gleich.", "The tram is coming soon.", None, None, None),
    ("Haltestelle", "die", "Haltestellen", "stop (bus/tram)", "NOUN", "A1", "TRAVEL", "Die Haltestelle ist dort.", "The stop is over there.", None, None, None),
    ("Fahrkarte", "die", "Fahrkarten", "ticket (travel)", "NOUN", "A1", "TRAVEL", "Ich brauche eine Fahrkarte.", "I need a ticket.", "Die Fahrkarten sind teuer.", "The tickets are expensive.", None),
    ("Karte", "die", "Karten", "map / card", "NOUN", "A1", "TRAVEL", "Hast du eine Karte von Berlin?", "Do you have a map of Berlin?", None, None, "Also: card."),
    ("Hotel", "das", "Hotels", "hotel", "NOUN", "A1", "TRAVEL", "Wir übernachten im Hotel.", "We stay overnight at the hotel.", None, None, None),
    ("Reise", "die", "Reisen", "trip / journey", "NOUN", "A1", "TRAVEL", "Die Reise war schön.", "The trip was nice.", None, None, None),
    ("Urlaub", "der", "Urlaube", "vacation / holiday", "NOUN", "A1", "TRAVEL", "Wir machen Urlaub in Italien.", "We are on holiday in Italy.", None, None, None),
    ("Pass", "der", "Pässe", "passport", "NOUN", "A1", "TRAVEL", "Wo ist dein Pass?", "Where is your passport?", None, None, None),
    ("Koffer", "der", "Koffer", "suitcase", "NOUN", "A1", "TRAVEL", "Der Koffer ist schwer.", "The suitcase is heavy.", "Die Koffer sind voll.", "The suitcases are full.", None),
    ("Tasche", "die", "Taschen", "bag", "NOUN", "A1", "TRAVEL", "Meine Tasche ist blau.", "My bag is blue.", "Die Taschen sind neu.", "The bags are new.", None),
    ("Richtung", "die", "Richtungen", "direction", "NOUN", "A1", "TRAVEL", "In welche Richtung ist der Bahnhof?", "Which direction is the station?", None, None, None),
    ("links", None, None, "left", "ADVERB", "A1", "TRAVEL", "Gehen Sie links.", "Go left.", None, None, None),
    ("rechts", None, None, "right", "ADVERB", "A1", "TRAVEL", "Das Café ist rechts.", "The café is on the right.", None, None, None),
    ("geradeaus", None, None, "straight ahead", "ADVERB", "A1", "TRAVEL", "Bitte geradeaus gehen.", "Please go straight ahead.", None, None, None),
    ("weit", None, None, "far", "ADJECTIVE", "A1", "TRAVEL", "Ist es weit zum Bahnhof?", "Is it far to the station?", None, None, None),
    ("nah", None, None, "near", "ADJECTIVE", "A1", "TRAVEL", "Der Laden ist nah.", "The shop is near.", None, None, None),
    ("ankommen", None, None, "to arrive", "VERB", "A1", "TRAVEL", "Der Zug kommt um zehn an.", "The train arrives at ten.", None, None, "Separable: ankommen."),
    ("abfahren", None, None, "to depart", "VERB", "A1", "TRAVEL", "Der Bus fährt um acht ab.", "The bus departs at eight.", None, None, "Separable: abfahren."),
    ("reisen", None, None, "to travel", "VERB", "A1", "TRAVEL", "Wir reisen nach Spanien.", "We travel to Spain.", None, None, None),
    ("fliegen", None, None, "to fly", "VERB", "A1", "TRAVEL", "Ich fliege nach Berlin.", "I fly to Berlin.", None, None, None),
    # --- PEOPLE ---
    ("Mutter", "die", "Mütter", "mother", "NOUN", "A1", "PEOPLE", "Meine Mutter kocht gut.", "My mother cooks well.", None, None, None),
    ("Vater", "der", "Väter", "father", "NOUN", "A1", "PEOPLE", "Mein Vater arbeitet hier.", "My father works here.", None, None, None),
    ("Eltern", "die", "Eltern", "parents", "NOUN", "A1", "PEOPLE", "Meine Eltern wohnen in Hamburg.", "My parents live in Hamburg.", None, None, "Plural only."),
    ("Bruder", "der", "Brüder", "brother", "NOUN", "A1", "PEOPLE", "Mein Bruder heißt Tom.", "My brother's name is Tom.", "Meine Brüder sind jung.", "My brothers are young.", None),
    ("Schwester", "die", "Schwestern", "sister", "NOUN", "A1", "PEOPLE", "Meine Schwester lernt Deutsch.", "My sister is learning German.", None, None, None),
    ("Sohn", "der", "Söhne", "son", "NOUN", "A1", "PEOPLE", "Ihr Sohn geht zur Schule.", "Their son goes to school.", None, None, None),
    ("Tochter", "die", "Töchter", "daughter", "NOUN", "A1", "PEOPLE", "Unsere Tochter ist fünf.", "Our daughter is five.", None, None, None),
    ("Oma", "die", "Omas", "grandma", "NOUN", "A1", "PEOPLE", "Die Oma liest ein Buch.", "Grandma is reading a book.", None, None, None),
    ("Opa", "der", "Opas", "grandpa", "NOUN", "A1", "PEOPLE", "Der Opa erzählt Geschichten.", "Grandpa tells stories.", None, None, None),
    ("Mannschaft", "die", "Mannschaften", "team", "NOUN", "A2", "PEOPLE", "Unsere Mannschaft spielt gut.", "Our team plays well.", None, None, None),
    ("Lehrer", "der", "Lehrer", "teacher (m.)", "NOUN", "A1", "SCHOOL_WORK", "Der Lehrer erklärt die Aufgabe.", "The teacher explains the exercise.", None, None, None),
    ("Lehrerin", "die", "Lehrerinnen", "teacher (f.)", "NOUN", "A1", "SCHOOL_WORK", "Die Lehrerin ist nett.", "The teacher is nice.", None, None, None),
    ("Schüler", "der", "Schüler", "student / pupil (m.)", "NOUN", "A1", "SCHOOL_WORK", "Der Schüler schreibt.", "The student is writing.", None, None, None),
    ("Schülerin", "die", "Schülerinnen", "student / pupil (f.)", "NOUN", "A1", "SCHOOL_WORK", "Die Schülerin liest laut.", "The student reads aloud.", None, None, None),
    ("Kollege", "der", "Kollegen", "colleague (m.)", "NOUN", "A1", "SCHOOL_WORK", "Mein Kollege hilft mir.", "My colleague helps me.", None, None, None),
    ("Kollegin", "die", "Kolleginnen", "colleague (f.)", "NOUN", "A1", "SCHOOL_WORK", "Meine Kollegin kommt später.", "My colleague is coming later.", None, None, None),
    ("Arzt", "der", "Ärzte", "doctor (m.)", "NOUN", "A1", "PEOPLE", "Der Arzt kommt gleich.", "The doctor is coming soon.", None, None, None),
    ("Ärztin", "die", "Ärztinnen", "doctor (f.)", "NOUN", "A1", "PEOPLE", "Die Ärztin ist freundlich.", "The doctor is friendly.", None, None, None),
    ("Person", "die", "Personen", "person", "NOUN", "A1", "PEOPLE", "Wie viele Personen?", "How many people?", None, None, None),
    ("Leute", "die", "Leute", "people", "NOUN", "A1", "PEOPLE", "Viele Leute sind hier.", "Many people are here.", None, None, "Plural only."),
    ("jung", None, None, "young", "ADJECTIVE", "A1", "PEOPLE", "Sie ist noch jung.", "She is still young.", None, None, None),
    ("verheiratet", None, None, "married", "ADJECTIVE", "A1", "PEOPLE", "Sind Sie verheiratet?", "Are you married?", None, None, None),
    ("allein", None, None, "alone", "ADJECTIVE", "A1", "PEOPLE", "Ich wohne allein.", "I live alone.", None, None, None),
    ("helfen", None, None, "to help", "VERB", "A1", "PEOPLE", "Kannst du mir helfen?", "Can you help me?", None, None, "Takes dative: jemandem helfen."),
    ("treffen", None, None, "to meet", "VERB", "A1", "PEOPLE", "Wir treffen uns um sechs.", "We meet at six.", None, None, None),
    ("kennen", None, None, "to know (a person/place)", "VERB", "A1", "PEOPLE", "Kennst du Anna?", "Do you know Anna?", None, None, None),
    # --- TIME ---
    ("Stunde", "die", "Stunden", "hour", "NOUN", "A1", "TIME", "Die Stunde ist vorbei.", "The hour is over.", "Zwei Stunden später.", "Two hours later.", None),
    ("Minute", "die", "Minuten", "minute", "NOUN", "A1", "TIME", "Bitte warte eine Minute.", "Please wait a minute.", None, None, None),
    ("Sekunde", "die", "Sekunden", "second", "NOUN", "A1", "TIME", "Nur eine Sekunde!", "Just a second!", None, None, None),
    ("Uhr", "die", "Uhren", "clock / o'clock", "NOUN", "A1", "TIME", "Es ist drei Uhr.", "It is three o'clock.", None, None, None),
    ("Montag", "der", "Montage", "Monday", "NOUN", "A1", "TIME", "Am Montag arbeite ich.", "I work on Monday.", None, None, None),
    ("Dienstag", "der", "Dienstage", "Tuesday", "NOUN", "A1", "TIME", "Am Dienstag habe ich Zeit.", "I have time on Tuesday.", None, None, None),
    ("Mittwoch", "der", "Mittwoche", "Wednesday", "NOUN", "A1", "TIME", "Mittwoch ist mein Lieblingstag.", "Wednesday is my favorite day.", None, None, None),
    ("Donnerstag", "der", "Donnerstage", "Thursday", "NOUN", "A1", "TIME", "Am Donnerstag kommen wir.", "We are coming on Thursday.", None, None, None),
    ("Freitag", "der", "Freitage", "Friday", "NOUN", "A1", "TIME", "Am Freitag ist Party.", "There is a party on Friday.", None, None, None),
    ("Samstag", "der", "Samstage", "Saturday", "NOUN", "A1", "TIME", "Am Samstag schlafe ich aus.", "I sleep in on Saturday.", None, None, None),
    ("Sonntag", "der", "Sonntage", "Sunday", "NOUN", "A1", "TIME", "Am Sonntag ist Ruhetag.", "Sunday is a rest day.", None, None, None),
    ("Wochenende", "das", "Wochenenden", "weekend", "NOUN", "A1", "TIME", "Am Wochenende fahren wir weg.", "On the weekend we go away.", None, None, None),
    ("gestern", None, None, "yesterday", "ADVERB", "A1", "TIME", "Gestern war ich zu Hause.", "Yesterday I was at home.", None, None, None),
    ("heute Abend", None, None, "this evening", "ADVERB", "A1", "TIME", "Heute Abend esse ich aus.", "This evening I eat out.", None, None, None),
    ("bald", None, None, "soon", "ADVERB", "A1", "TIME", "Bis bald!", "See you soon!", None, None, None),
    ("später", None, None, "later", "ADVERB", "A1", "TIME", "Bis später!", "See you later!", None, None, None),
    ("immer", None, None, "always", "ADVERB", "A1", "TIME", "Ich lerne immer Deutsch.", "I always study German.", None, None, None),
    ("nie", None, None, "never", "ADVERB", "A1", "TIME", "Ich trinke nie Alkohol.", "I never drink alcohol.", None, None, None),
    ("oft", None, None, "often", "ADVERB", "A1", "TIME", "Wir gehen oft spazieren.", "We often go for a walk.", None, None, None),
    ("manchmal", None, None, "sometimes", "ADVERB", "A1", "TIME", "Manchmal koche ich.", "Sometimes I cook.", None, None, None),
    ("früh", None, None, "early", "ADJECTIVE", "A1", "TIME", "Ich stehe früh auf.", "I get up early.", None, None, None),
    ("spät", None, None, "late", "ADJECTIVE", "A1", "TIME", "Es ist schon spät.", "It is already late.", None, None, None),
    ("warten", None, None, "to wait", "VERB", "A1", "TIME", "Bitte warte hier.", "Please wait here.", None, None, None),
    ("beginnen", None, None, "to begin", "VERB", "A1", "TIME", "Der Kurs beginnt um neun.", "The course begins at nine.", None, None, None),
    ("enden", None, None, "to end", "VERB", "A1", "TIME", "Der Film endet um zehn.", "The film ends at ten.", None, None, None),
    # --- SCHOOL_WORK ---
    ("Unterricht", "der", "Unterrichte", "class / lesson", "NOUN", "A1", "SCHOOL_WORK", "Der Unterricht beginnt um acht.", "Class begins at eight.", None, None, None),
    ("Aufgabe", "die", "Aufgaben", "task / homework exercise", "NOUN", "A1", "SCHOOL_WORK", "Die Aufgabe ist schwer.", "The exercise is hard.", "Die Aufgaben sind fertig.", "The exercises are done.", None),
    ("Hausaufgabe", "die", "Hausaufgaben", "homework", "NOUN", "A1", "SCHOOL_WORK", "Ich mache meine Hausaufgaben.", "I do my homework.", None, None, "Often plural."),
    ("Prüfung", "die", "Prüfungen", "exam / test", "NOUN", "A1", "SCHOOL_WORK", "Die Prüfung ist am Freitag.", "The exam is on Friday.", None, None, None),
    ("Frage", "die", "Fragen", "question", "NOUN", "A1", "SCHOOL_WORK", "Ich habe eine Frage.", "I have a question.", "Hast du Fragen?", "Do you have questions?", None),
    ("Antwort", "die", "Antworten", "answer", "NOUN", "A1", "SCHOOL_WORK", "Die Antwort ist richtig.", "The answer is correct.", None, None, None),
    ("Wort", "das", "Wörter", "word", "NOUN", "A1", "SCHOOL_WORK", "Dieses Wort ist neu.", "This word is new.", "Die Wörter sind wichtig.", "The words are important.", "Wörter = dictionary words; Worte = spoken words."),
    ("Satz", "der", "Sätze", "sentence", "NOUN", "A1", "SCHOOL_WORK", "Schreib einen Satz.", "Write a sentence.", None, None, None),
    ("Sprache", "die", "Sprachen", "language", "NOUN", "A1", "SCHOOL_WORK", "Deutsch ist eine schöne Sprache.", "German is a beautiful language.", None, None, None),
    ("Wörterbuch", "das", "Wörterbücher", "dictionary", "NOUN", "A1", "SCHOOL_WORK", "Ich brauche ein Wörterbuch.", "I need a dictionary.", None, None, None),
    ("Computer", "der", "Computer", "computer", "NOUN", "A1", "SCHOOL_WORK", "Der Computer ist neu.", "The computer is new.", None, None, None),
    ("Handy", "das", "Handys", "mobile phone", "NOUN", "A1", "SCHOOL_WORK", "Mein Handy ist kaputt.", "My phone is broken.", None, None, None),
    ("E-Mail", "die", "E-Mails", "email", "NOUN", "A1", "SCHOOL_WORK", "Ich schreibe eine E-Mail.", "I write an email.", None, None, None),
    ("Büro", "das", "Büros", "office", "NOUN", "A1", "SCHOOL_WORK", "Ich arbeite im Büro.", "I work in the office.", None, None, None),
    ("Beruf", "der", "Berufe", "profession / job", "NOUN", "A1", "SCHOOL_WORK", "Was ist dein Beruf?", "What is your job?", None, None, None),
    ("Chef", "der", "Chefs", "boss (m.)", "NOUN", "A1", "SCHOOL_WORK", "Mein Chef ist streng.", "My boss is strict.", None, None, None),
    ("Chefin", "die", "Chefinnen", "boss (f.)", "NOUN", "A1", "SCHOOL_WORK", "Die Chefin kommt morgen.", "The boss is coming tomorrow.", None, None, None),
    ("Pause", "die", "Pausen", "break", "NOUN", "A1", "SCHOOL_WORK", "Wir machen eine Pause.", "We take a break.", None, None, None),
    ("schwer", None, None, "difficult / heavy", "ADJECTIVE", "A1", "SCHOOL_WORK", "Die Prüfung war schwer.", "The exam was difficult.", None, None, None),
    ("leicht", None, None, "easy / light", "ADJECTIVE", "A1", "SCHOOL_WORK", "Die Aufgabe ist leicht.", "The exercise is easy.", None, None, None),
    ("üben", None, None, "to practice", "VERB", "A1", "SCHOOL_WORK", "Ich übe jeden Tag.", "I practice every day.", None, None, None),
    ("studieren", None, None, "to study (at university)", "VERB", "A1", "SCHOOL_WORK", "Sie studiert in München.", "She studies in Munich.", None, None, None),
    ("erklären", None, None, "to explain", "VERB", "A1", "SCHOOL_WORK", "Kannst du das erklären?", "Can you explain that?", None, None, None),
    ("fragen", None, None, "to ask", "VERB", "A1", "SCHOOL_WORK", "Darf ich etwas fragen?", "May I ask something?", None, None, None),
    ("antworten", None, None, "to answer", "VERB", "A1", "SCHOOL_WORK", "Bitte antworte laut.", "Please answer loudly.", None, None, None),
    ("wissen", None, None, "to know (a fact)", "VERB", "A1", "SCHOOL_WORK", "Ich weiß das nicht.", "I don't know that.", None, None, None),
    # --- SHOPPING ---
    ("Geschäft", "das", "Geschäfte", "shop / business", "NOUN", "A1", "SHOPPING", "Das Geschäft ist geöffnet.", "The shop is open.", None, None, None),
    ("Supermarkt", "der", "Supermärkte", "supermarket", "NOUN", "A1", "SHOPPING", "Ich gehe in den Supermarkt.", "I go to the supermarket.", None, None, None),
    ("Bäckerei", "die", "Bäckereien", "bakery", "NOUN", "A1", "SHOPPING", "In der Bäckerei gibt es Brot.", "There is bread at the bakery.", None, None, None),
    ("Kunde", "der", "Kunden", "customer (m.)", "NOUN", "A1", "SHOPPING", "Der Kunde wartet.", "The customer is waiting.", None, None, None),
    ("Kundin", "die", "Kundinnen", "customer (f.)", "NOUN", "A1", "SHOPPING", "Die Kundin bezahlt.", "The customer is paying.", None, None, None),
    ("Rechnung", "die", "Rechnungen", "bill / invoice", "NOUN", "A1", "SHOPPING", "Die Rechnung, bitte.", "The bill, please.", None, None, None),
    ("Quittung", "die", "Quittungen", "receipt", "NOUN", "A1", "SHOPPING", "Kann ich eine Quittung haben?", "Can I have a receipt?", None, None, None),
    ("Kasse", "die", "Kassen", "checkout / cash register", "NOUN", "A1", "SHOPPING", "Bitte an die Kasse.", "Please go to the checkout.", None, None, None),
    ("Angebot", "das", "Angebote", "offer / special", "NOUN", "A1", "SHOPPING", "Heute gibt es ein Angebot.", "There is a special offer today.", None, None, None),
    ("Rabatt", "der", "Rabatte", "discount", "NOUN", "A1", "SHOPPING", "Gibt es einen Rabatt?", "Is there a discount?", None, None, None),
    ("Größe", "die", "Größen", "size", "NOUN", "A1", "SHOPPING", "Welche Größe haben Sie?", "What size do you have?", None, None, None),
    ("Farbe", "die", "Farben", "color", "NOUN", "A1", "SHOPPING", "Welche Farbe möchten Sie?", "Which color would you like?", None, None, None),
    ("teuer", None, None, "expensive", "ADJECTIVE", "A1", "SHOPPING", "Das ist zu teuer.", "That is too expensive.", None, None, None),
    ("billig", None, None, "cheap", "ADJECTIVE", "A1", "SHOPPING", "Das Hemd ist billig.", "The shirt is cheap.", None, None, None),
    ("kosten", None, None, "to cost", "VERB", "A1", "SHOPPING", "Was kostet das?", "How much does that cost?", None, None, None),
    ("bezahlen", None, None, "to pay", "VERB", "A1", "SHOPPING", "Ich möchte bar bezahlen.", "I would like to pay cash.", None, None, None),
    ("verkaufen", None, None, "to sell", "VERB", "A1", "SHOPPING", "Sie verkaufen Obst.", "They sell fruit.", None, None, None),
    ("suchen", None, None, "to look for", "VERB", "A1", "SHOPPING", "Ich suche ein Geschenk.", "I am looking for a gift.", None, None, None),
    ("finden", None, None, "to find", "VERB", "A1", "SHOPPING", "Ich finde nichts.", "I can't find anything.", None, None, None),
    ("probieren", None, None, "to try on / try", "VERB", "A1", "SHOPPING", "Kann ich das proberen?", "Can I try that?", None, None, None),
    ("öffnen", None, None, "to open (shop hours sense also)", "VERB", "A2", "SHOPPING", "Das Geschäft öffnet um neun.", "The shop opens at nine.", None, None, None),
    # Wait - öffnen already in HOME. Skip duplicate - I'll filter later
]

# Fix: remove accidental duplicate öffnen at end - I'll filter in code by lemma+article

MORE: list[tuple] = [
    # --- ESSENTIALS (core verbs, function words, daily life) ---
    ("wo", None, None, "where", "ADVERB", "A1", "ESSENTIALS", "Wo wohnst du?", "Where do you live?", None, None, None),
    ("was", None, None, "what", "PRONOUN", "A1", "ESSENTIALS", "Was ist das?", "What is that?", None, None, None),
    ("wer", None, None, "who", "PRONOUN", "A1", "ESSENTIALS", "Wer ist das?", "Who is that?", None, None, None),
    ("wie", None, None, "how", "ADVERB", "A1", "ESSENTIALS", "Wie geht es dir?", "How are you?", None, None, None),
    ("wann", None, None, "when", "ADVERB", "A1", "ESSENTIALS", "Wann kommst du?", "When are you coming?", None, None, None),
    ("warum", None, None, "why", "ADVERB", "A1", "ESSENTIALS", "Warum lernst du Deutsch?", "Why are you learning German?", None, None, None),
    ("welche", None, None, "which", "PRONOUN", "A1", "ESSENTIALS", "Welche Farbe magst du?", "Which color do you like?", None, None, None),
    ("viel", None, None, "much / a lot", "ADJECTIVE", "A1", "ESSENTIALS", "Ich habe viel Zeit.", "I have a lot of time.", None, None, None),
    ("wenig", None, None, "little / few", "ADJECTIVE", "A1", "ESSENTIALS", "Ich habe wenig Geld.", "I have little money.", None, None, None),
    ("alle", None, None, "all / everyone", "PRONOUN", "A1", "ESSENTIALS", "Alle kommen mit.", "Everyone is coming along.", None, None, None),
    ("nichts", None, None, "nothing", "PRONOUN", "A1", "ESSENTIALS", "Ich höre nichts.", "I hear nothing.", None, None, None),
    ("etwas", None, None, "something", "PRONOUN", "A1", "ESSENTIALS", "Möchtest du etwas trinken?", "Would you like something to drink?", None, None, None),
    ("noch", None, None, "still / yet / another", "ADVERB", "A1", "ESSENTIALS", "Ich habe noch Zeit.", "I still have time.", None, None, None),
    ("schon", None, None, "already", "ADVERB", "A1", "ESSENTIALS", "Bist du schon fertig?", "Are you already done?", None, None, None),
    ("nur", None, None, "only", "ADVERB", "A1", "ESSENTIALS", "Ich trinke nur Wasser.", "I only drink water.", None, None, None),
    ("nicht", None, None, "not", "PARTICLE", "A1", "ESSENTIALS", "Ich bin nicht müde.", "I am not tired.", None, None, None),
    ("kein", None, None, "no / not a", "OTHER", "A1", "ESSENTIALS", "Ich habe kein Auto.", "I don't have a car.", None, None, "Declines like ein."),
    ("mit", None, None, "with", "PREPOSITION", "A1", "ESSENTIALS", "Ich fahre mit dem Bus.", "I go by bus.", None, None, "Takes dative."),
    ("ohne", None, None, "without", "PREPOSITION", "A1", "ESSENTIALS", "Kaffee ohne Milch, bitte.", "Coffee without milk, please.", None, None, None),
    ("bei", None, None, "at / with (someone)", "PREPOSITION", "A1", "ESSENTIALS", "Ich bin bei Freunden.", "I am at friends' place.", None, None, "Takes dative."),
    ("nach", None, None, "to / after", "PREPOSITION", "A1", "ESSENTIALS", "Wir fahren nach Berlin.", "We are going to Berlin.", None, None, "Cities/countries: nach."),
    ("zu", None, None, "to", "PREPOSITION", "A1", "ESSENTIALS", "Ich gehe zu Anna.", "I am going to Anna's.", None, None, "Takes dative."),
    ("aus", None, None, "from / out of", "PREPOSITION", "A1", "ESSENTIALS", "Ich komme aus Spanien.", "I come from Spain.", None, None, None),
    ("an", None, None, "at / on (vertical)", "PREPOSITION", "A1", "ESSENTIALS", "Das Bild hängt an der Wand.", "The picture hangs on the wall.", None, None, None),
    ("über", None, None, "over / about", "PREPOSITION", "A1", "ESSENTIALS", "Wir sprechen über die Reise.", "We talk about the trip.", None, None, None),
    ("unter", None, None, "under", "PREPOSITION", "A1", "ESSENTIALS", "Der Hund liegt unter dem Tisch.", "The dog lies under the table.", None, None, None),
    ("zwischen", None, None, "between", "PREPOSITION", "A1", "ESSENTIALS", "Ich sitze zwischen Tom und Anna.", "I sit between Tom and Anna.", None, None, None),
    ("vor", None, None, "in front of / before", "PREPOSITION", "A1", "ESSENTIALS", "Das Auto steht vor dem Haus.", "The car is in front of the house.", None, None, None),
    ("hinter", None, None, "behind", "PREPOSITION", "A1", "ESSENTIALS", "Der Garten ist hinter dem Haus.", "The garden is behind the house.", None, None, None),
    ("neben", None, None, "next to", "PREPOSITION", "A1", "ESSENTIALS", "Das Café ist neben der Bank.", "The café is next to the bank.", None, None, None),
    ("geben", None, None, "to give / there is", "VERB", "A1", "ESSENTIALS", "Es gibt einen Park.", "There is a park.", None, None, "es gibt = there is/are."),
    ("nehmen", None, None, "to take", "VERB", "A1", "ESSENTIALS", "Ich nehme den Bus.", "I take the bus.", None, None, None),
    ("bringen", None, None, "to bring", "VERB", "A1", "ESSENTIALS", "Bringst du Brot mit?", "Are you bringing bread?", None, None, None),
    ("stehen", None, None, "to stand", "VERB", "A1", "ESSENTIALS", "Wir stehen an der Haltestelle.", "We stand at the stop.", None, None, None),
    ("sitzen", None, None, "to sit", "VERB", "A1", "ESSENTIALS", "Bitte setzen Sie sich.", "Please sit down.", None, None, None),
    ("liegen", None, None, "to lie / be located", "VERB", "A1", "ESSENTIALS", "Das Buch liegt auf dem Tisch.", "The book is lying on the table.", None, None, None),
    ("bleiben", None, None, "to stay", "VERB", "A1", "ESSENTIALS", "Ich bleibe zu Hause.", "I am staying at home.", None, None, None),
    ("werden", None, None, "to become / will", "VERB", "A1", "ESSENTIALS", "Es wird kalt.", "It is getting cold.", None, None, None),
    ("dürfen", None, None, "may / to be allowed to", "VERB", "A1", "ESSENTIALS", "Darf ich herein?", "May I come in?", None, None, None),
    ("sollen", None, None, "should / ought to", "VERB", "A1", "ESSENTIALS", "Was soll ich machen?", "What should I do?", None, None, None),
    ("gefallen", None, None, "to please / like", "VERB", "A1", "ESSENTIALS", "Das gefällt mir.", "I like that.", None, None, "Subject = thing liked; dative person."),
    ("lieben", None, None, "to love", "VERB", "A1", "ESSENTIALS", "Ich liebe dieses Land.", "I love this country.", None, None, None),
    ("spielen", None, None, "to play", "VERB", "A1", "ESSENTIALS", "Die Kinder spielen draußen.", "The children play outside.", None, None, None),
    ("schlafen", None, None, "to sleep", "VERB", "A1", "ESSENTIALS", "Ich schlafe acht Stunden.", "I sleep eight hours.", None, None, None),
    ("aufstehen", None, None, "to get up", "VERB", "A1", "ESSENTIALS", "Ich stehe um sieben auf.", "I get up at seven.", None, None, "Separable: aufstehen."),
    ("einkaufen", None, None, "to shop / go shopping", "VERB", "A1", "SHOPPING", "Wir gehen einkaufen.", "We are going shopping.", None, None, None),
    ("telefonieren", None, None, "to phone", "VERB", "A1", "ESSENTIALS", "Ich telefoniere mit Mama.", "I phone Mom.", None, None, None),
    ("besuchen", None, None, "to visit", "VERB", "A1", "ESSENTIALS", "Wir besuchen Freunde.", "We visit friends.", None, None, None),
    ("erzählen", None, None, "to tell / narrate", "VERB", "A1", "ESSENTIALS", "Erzähl mir etwas!", "Tell me something!", None, None, None),
    ("zeigen", None, None, "to show", "VERB", "A1", "ESSENTIALS", "Zeig mir das Foto.", "Show me the photo.", None, None, None),
    # --- DESCRIPTIONS ---
    ("schön", None, None, "beautiful / nice", "ADJECTIVE", "A1", "DESCRIPTIONS", "Das Wetter ist schön.", "The weather is nice.", None, None, None),
    ("hässlich", None, None, "ugly", "ADJECTIVE", "A1", "DESCRIPTIONS", "Das Bild ist hässlich.", "The picture is ugly.", None, None, None),
    ("lang", None, None, "long", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Weg ist lang.", "The path is long.", None, None, None),
    ("kurz", None, None, "short", "ADJECTIVE", "A1", "DESCRIPTIONS", "Die Pause ist kurz.", "The break is short.", None, None, None),
    ("hoch", None, None, "high / tall", "ADJECTIVE", "A1", "DESCRIPTIONS", "Das Haus ist hoch.", "The house is tall.", None, None, None),
    ("niedrig", None, None, "low", "ADJECTIVE", "A1", "DESCRIPTIONS", "Die Decke ist niedrig.", "The ceiling is low.", None, None, None),
    ("breit", None, None, "wide", "ADJECTIVE", "A1", "DESCRIPTIONS", "Die Straße ist breit.", "The street is wide.", None, None, None),
    ("eng", None, None, "narrow", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Weg ist eng.", "The path is narrow.", None, None, None),
    ("schnell", None, None, "fast", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Zug ist schnell.", "The train is fast.", None, None, None),
    ("langsam", None, None, "slow", "ADJECTIVE", "A1", "DESCRIPTIONS", "Bitte sprich langsam.", "Please speak slowly.", None, None, None),
    ("laut", None, None, "loud", "ADJECTIVE", "A1", "DESCRIPTIONS", "Die Musik ist laut.", "The music is loud.", None, None, None),
    ("leise", None, None, "quiet / soft", "ADJECTIVE", "A1", "DESCRIPTIONS", "Bitte sei leise.", "Please be quiet.", None, None, None),
    ("warm", None, None, "warm", "ADJECTIVE", "A1", "DESCRIPTIONS", "Heute ist es warm.", "It is warm today.", None, None, None),
    ("kalt", None, None, "cold", "ADJECTIVE", "A1", "DESCRIPTIONS", "Im Winter ist es kalt.", "In winter it is cold.", None, None, None),
    ("heiß", None, None, "hot", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Tee ist heiß.", "The tea is hot.", None, None, None),
    ("kühl", None, None, "cool", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Wind ist kühl.", "The wind is cool.", None, None, None),
    ("hell", None, None, "bright / light", "ADJECTIVE", "A1", "DESCRIPTIONS", "Das Zimmer ist hell.", "The room is bright.", None, None, None),
    ("dunkel", None, None, "dark", "ADJECTIVE", "A1", "DESCRIPTIONS", "Es wird dunkel.", "It is getting dark.", None, None, None),
    ("voll", None, None, "full", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Bus ist voll.", "The bus is full.", None, None, None),
    ("leer", None, None, "empty", "ADJECTIVE", "A1", "DESCRIPTIONS", "Die Flasche ist leer.", "The bottle is empty.", None, None, None),
    ("offen", None, None, "open", "ADJECTIVE", "A1", "DESCRIPTIONS", "Das Fenster ist offen.", "The window is open.", None, None, None),
    ("geschlossen", None, None, "closed", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Laden ist geschlossen.", "The shop is closed.", None, None, None),
    ("frei", None, None, "free / available", "ADJECTIVE", "A1", "DESCRIPTIONS", "Ist der Platz frei?", "Is the seat free?", None, None, None),
    ("besetzt", None, None, "occupied / taken", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Platz ist besetzt.", "The seat is taken.", None, None, None),
    ("kaputt", None, None, "broken", "ADJECTIVE", "A1", "DESCRIPTIONS", "Mein Handy ist kaputt.", "My phone is broken.", None, None, None),
    ("fertig", None, None, "finished / ready", "ADJECTIVE", "A1", "DESCRIPTIONS", "Ich bin fertig.", "I am finished.", None, None, None),
    ("müde", None, None, "tired", "ADJECTIVE", "A1", "DESCRIPTIONS", "Ich bin müde.", "I am tired.", None, None, None),
    ("glücklich", None, None, "happy", "ADJECTIVE", "A1", "DESCRIPTIONS", "Sie sieht glücklich aus.", "She looks happy.", None, None, None),
    ("traurig", None, None, "sad", "ADJECTIVE", "A1", "DESCRIPTIONS", "Warum bist du traurig?", "Why are you sad?", None, None, None),
    ("interessant", None, None, "interesting", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Film ist interessant.", "The film is interesting.", None, None, None),
    ("langweilig", None, None, "boring", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Unterricht war langweilig.", "The class was boring.", None, None, None),
    ("möglich", None, None, "possible", "ADJECTIVE", "A1", "DESCRIPTIONS", "Ist das möglich?", "Is that possible?", None, None, None),
    ("unmöglich", None, None, "impossible", "ADJECTIVE", "A2", "DESCRIPTIONS", "Das ist unmöglich.", "That is impossible.", None, None, None),
    ("richtig", None, None, "correct / right", "ADJECTIVE", "A1", "DESCRIPTIONS", "Die Antwort ist richtig.", "The answer is correct.", None, None, None),
    ("falsch", None, None, "wrong", "ADJECTIVE", "A1", "DESCRIPTIONS", "Das ist falsch.", "That is wrong.", None, None, None),
    # clothing / shopping nouns
    ("Hemd", "das", "Hemden", "shirt", "NOUN", "A1", "SHOPPING", "Das Hemd ist blau.", "The shirt is blue.", None, None, None),
    ("Hose", "die", "Hosen", "pants / trousers", "NOUN", "A1", "SHOPPING", "Die Hose passt gut.", "The pants fit well.", None, None, None),
    ("Jacke", "die", "Jacken", "jacket", "NOUN", "A1", "SHOPPING", "Die Jacke ist warm.", "The jacket is warm.", None, None, None),
    ("Mantel", "der", "Mäntel", "coat", "NOUN", "A1", "SHOPPING", "Im Winter trage ich einen Mantel.", "In winter I wear a coat.", None, None, None),
    ("Schuh", "der", "Schuhe", "shoe", "NOUN", "A1", "SHOPPING", "Der Schuh ist zu klein.", "The shoe is too small.", "Die Schuhe sind neu.", "The shoes are new.", None),
    ("Socke", "die", "Socken", "sock", "NOUN", "A1", "SHOPPING", "Wo ist die andere Socke?", "Where is the other sock?", "Die Socken sind schwarz.", "The socks are black.", None),
    ("Hut", "der", "Hüte", "hat", "NOUN", "A1", "SHOPPING", "Er trägt einen Hut.", "He is wearing a hat.", None, None, None),
    ("Kleid", "das", "Kleider", "dress", "NOUN", "A1", "SHOPPING", "Das Kleid ist schön.", "The dress is beautiful.", None, None, None),
    ("Rock", "der", "Röcke", "skirt", "NOUN", "A1", "SHOPPING", "Der Rock ist kurz.", "The skirt is short.", None, None, None),
    ("Pullover", "der", "Pullover", "sweater", "NOUN", "A1", "SHOPPING", "Der Pullover ist weich.", "The sweater is soft.", None, None, None),
    ("tragen", None, None, "to wear / carry", "VERB", "A1", "SHOPPING", "Was trägst du heute?", "What are you wearing today?", None, None, None),
    ("passen", None, None, "to fit / suit", "VERB", "A1", "SHOPPING", "Die Hose passt perfekt.", "The pants fit perfectly.", None, None, None),
    # body / health essentials
    ("Kopf", "der", "Köpfe", "head", "NOUN", "A1", "ESSENTIALS", "Mein Kopf tut weh.", "My head hurts.", None, None, None),
    ("Hand", "die", "Hände", "hand", "NOUN", "A1", "ESSENTIALS", "Gib mir die Hand.", "Give me your hand.", "Wasche die Hände.", "Wash your hands.", None),
    ("Fuß", "der", "Füße", "foot", "NOUN", "A1", "ESSENTIALS", "Mein Fuß ist müde.", "My foot is tired.", None, None, None),
    ("Auge", "das", "Augen", "eye", "NOUN", "A1", "ESSENTIALS", "Sie hat blaue Augen.", "She has blue eyes.", None, None, None),
    ("Ohr", "das", "Ohren", "ear", "NOUN", "A1", "ESSENTIALS", "Ich höre mit dem Ohr.", "I hear with my ear.", None, None, None),
    ("Mund", "der", "Münder", "mouth", "NOUN", "A1", "ESSENTIALS", "Mach den Mund auf.", "Open your mouth.", None, None, None),
    ("Nase", "die", "Nasen", "nose", "NOUN", "A1", "ESSENTIALS", "Meine Nase ist kalt.", "My nose is cold.", None, None, None),
    ("Körper", "der", "Körper", "body", "NOUN", "A1", "ESSENTIALS", "Sport ist gut für den Körper.", "Sport is good for the body.", None, None, None),
    ("Schmerz", "der", "Schmerzen", "pain", "NOUN", "A1", "ESSENTIALS", "Ich habe Schmerzen.", "I have pain.", None, None, None),
    ("krank", None, None, "ill / sick", "ADJECTIVE", "A1", "ESSENTIALS", "Ich bin krank.", "I am sick.", None, None, None),
    ("gesund", None, None, "healthy", "ADJECTIVE", "A1", "ESSENTIALS", "Er isst gesund.", "He eats healthily.", None, None, None),
    ("weh", None, None, "hurt (in wehtun)", "OTHER", "A1", "ESSENTIALS", "Der Zahn tut weh.", "The tooth hurts.", None, None, "Common: wehtun."),
    ("Krankenhaus", "das", "Krankenhäuser", "hospital", "NOUN", "A1", "TRAVEL", "Sie arbeitet im Krankenhaus.", "She works at the hospital.", None, None, None),
    ("Apotheke", "die", "Apotheken", "pharmacy", "NOUN", "A1", "SHOPPING", "Die Apotheke ist um die Ecke.", "The pharmacy is around the corner.", None, None, None),
    ("Medizin", "die", "Medizinen", "medicine", "NOUN", "A1", "ESSENTIALS", "Ich brauche Medizin.", "I need medicine.", None, None, None),
    # places
    ("Park", "der", "Parks", "park", "NOUN", "A1", "TRAVEL", "Wir gehen in den Park.", "We go to the park.", None, None, None),
    ("Museum", "das", "Museen", "museum", "NOUN", "A1", "TRAVEL", "Das Museum ist interessant.", "The museum is interesting.", None, None, None),
    ("Kino", "das", "Kinos", "cinema", "NOUN", "A1", "TRAVEL", "Gehen wir ins Kino?", "Shall we go to the cinema?", None, None, None),
    ("Theater", "das", "Theater", "theater", "NOUN", "A1", "TRAVEL", "Das Theater beginnt um acht.", "The theater starts at eight.", None, None, None),
    ("Bank", "die", "Banken", "bank / bench", "NOUN", "A1", "TRAVEL", "Ich gehe zur Bank.", "I am going to the bank.", None, None, "Also: bench."),
    ("Post", "die", "Posten", "post office / mail", "NOUN", "A1", "TRAVEL", "Wo ist die Post?", "Where is the post office?", None, None, None),
    ("Polizei", "die", None, "police", "NOUN", "A1", "ESSENTIALS", "Ruf die Polizei!", "Call the police!", None, None, None),
    ("Feuerwehr", "die", None, "fire department", "NOUN", "A2", "ESSENTIALS", "Die Feuerwehr kommt schnell.", "The fire department comes quickly.", None, None, None),
    ("Kirche", "die", "Kirchen", "church", "NOUN", "A1", "TRAVEL", "Die Kirche ist alt.", "The church is old.", None, None, None),
    ("Brücke", "die", "Brücken", "bridge", "NOUN", "A1", "TRAVEL", "Wir gehen über die Brücke.", "We walk across the bridge.", None, None, None),
    ("Platz", "der", "Plätze", "square / place / seat", "NOUN", "A1", "TRAVEL", "Der Platz ist groß.", "The square is big.", None, None, None),
    ("Zentrum", "das", "Zentren", "center", "NOUN", "A1", "TRAVEL", "Wir wohnen im Zentrum.", "We live in the center.", None, None, None),
    ("Dorf", "das", "Dörfer", "village", "NOUN", "A1", "TRAVEL", "Sie kommt aus einem Dorf.", "She comes from a village.", None, None, None),
    ("Wald", "der", "Wälder", "forest", "NOUN", "A1", "TRAVEL", "Wir spazieren im Wald.", "We walk in the forest.", None, None, None),
    ("See", "der", "Seen", "lake", "NOUN", "A1", "TRAVEL", "Der See ist schön.", "The lake is beautiful.", None, None, "die See = sea."),
    ("Meer", "das", "Meere", "sea", "NOUN", "A1", "TRAVEL", "Im Sommer fahren wir ans Meer.", "In summer we go to the sea.", None, None, None),
    ("Berg", "der", "Berge", "mountain", "NOUN", "A1", "TRAVEL", "Der Berg ist hoch.", "The mountain is high.", None, None, None),
    ("Fluss", "der", "Flüsse", "river", "NOUN", "A1", "TRAVEL", "Der Fluss fließt durch die Stadt.", "The river flows through the city.", None, None, None),
    ("Insel", "die", "Inseln", "island", "NOUN", "A1", "TRAVEL", "Die Insel ist klein.", "The island is small.", None, None, None),
    ("Wetter", "das", None, "weather", "NOUN", "A1", "ESSENTIALS", "Wie ist das Wetter?", "How is the weather?", None, None, None),
    ("Sonne", "die", "Sonnen", "sun", "NOUN", "A1", "ESSENTIALS", "Die Sonne scheint.", "The sun is shining.", None, None, None),
    ("Regen", "der", None, "rain", "NOUN", "A1", "ESSENTIALS", "Heute gibt es Regen.", "There is rain today.", None, None, None),
    ("Schnee", "der", None, "snow", "NOUN", "A1", "ESSENTIALS", "Im Winter liegt Schnee.", "In winter there is snow.", None, None, None),
    ("Wind", "der", "Winde", "wind", "NOUN", "A1", "ESSENTIALS", "Der Wind ist stark.", "The wind is strong.", None, None, None),
    ("Wolke", "die", "Wolken", "cloud", "NOUN", "A1", "ESSENTIALS", "Es gibt viele Wolken.", "There are many clouds.", None, None, None),
    ("Himmel", "der", None, "sky / heaven", "NOUN", "A1", "ESSENTIALS", "Der Himmel ist blau.", "The sky is blue.", None, None, None),
    ("regnen", None, None, "to rain", "VERB", "A1", "ESSENTIALS", "Es regnet stark.", "It is raining hard.", None, None, None),
    ("scheinen", None, None, "to shine", "VERB", "A1", "ESSENTIALS", "Die Sonne scheint.", "The sun is shining.", None, None, None),
    # colors
    ("rot", None, None, "red", "ADJECTIVE", "A1", "DESCRIPTIONS", "Das Auto ist rot.", "The car is red.", None, None, None),
    ("blau", None, None, "blue", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Himmel ist blau.", "The sky is blue.", None, None, None),
    ("grün", None, None, "green", "ADJECTIVE", "A1", "DESCRIPTIONS", "Das Gras ist grün.", "The grass is green.", None, None, None),
    ("gelb", None, None, "yellow", "ADJECTIVE", "A1", "DESCRIPTIONS", "Die Banane ist gelb.", "The banana is yellow.", None, None, None),
    ("schwarz", None, None, "black", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Kaffee ist schwarz.", "The coffee is black.", None, None, None),
    ("weiß", None, None, "white", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Schnee ist weiß.", "The snow is white.", None, None, None),
    ("braun", None, None, "brown", "ADJECTIVE", "A1", "DESCRIPTIONS", "Das Brot ist braun.", "The bread is brown.", None, None, None),
    ("grau", None, None, "gray", "ADJECTIVE", "A1", "DESCRIPTIONS", "Der Himmel ist grau.", "The sky is gray.", None, None, None),
    ("orange", None, None, "orange (color)", "ADJECTIVE", "A1", "DESCRIPTIONS", "Die Jacke ist orange.", "The jacket is orange.", None, None, None),
    ("lila", None, None, "purple", "ADJECTIVE", "A1", "DESCRIPTIONS", "Die Blume ist lila.", "The flower is purple.", None, None, None),
    # numbers / quantity words as essentials
    ("eins", None, None, "one", "OTHER", "A1", "ESSENTIALS", "Ich habe nur eins.", "I only have one.", None, None, None),
    ("zwei", None, None, "two", "OTHER", "A1", "ESSENTIALS", "Wir sind zwei.", "There are two of us.", None, None, None),
    ("drei", None, None, "three", "OTHER", "A1", "ESSENTIALS", "Drei bitte.", "Three please.", None, None, None),
    ("vier", None, None, "four", "OTHER", "A1", "ESSENTIALS", "Wir brauchen vier Stühle.", "We need four chairs.", None, None, None),
    ("fünf", None, None, "five", "OTHER", "A1", "ESSENTIALS", "Es kostet fünf Euro.", "It costs five euros.", None, None, None),
    ("sechs", None, None, "six", "OTHER", "A1", "ESSENTIALS", "Um sechs Uhr.", "At six o'clock.", None, None, None),
    ("sieben", None, None, "seven", "OTHER", "A1", "ESSENTIALS", "Sieben Tage hat die Woche.", "A week has seven days.", None, None, None),
    ("acht", None, None, "eight", "OTHER", "A1", "ESSENTIALS", "Ich stehe um acht auf.", "I get up at eight.", None, None, None),
    ("neun", None, None, "nine", "OTHER", "A1", "ESSENTIALS", "Das Kind ist neun.", "The child is nine.", None, None, None),
    ("zehn", None, None, "ten", "OTHER", "A1", "ESSENTIALS", "Zehn Minuten bitte.", "Ten minutes please.", None, None, None),
    ("hundert", None, None, "hundred", "OTHER", "A1", "ESSENTIALS", "Es kostet hundert Euro.", "It costs a hundred euros.", None, None, None),
    ("tausend", None, None, "thousand", "OTHER", "A1", "ESSENTIALS", "Tausend Dank!", "A thousand thanks!", None, None, None),
    ("erste", None, None, "first", "ADJECTIVE", "A1", "ESSENTIALS", "Das ist die erste Lektion.", "That is the first lesson.", None, None, None),
    ("letzte", None, None, "last", "ADJECTIVE", "A1", "ESSENTIALS", "Das ist die letzte Seite.", "That is the last page.", None, None, None),
    ("nächste", None, None, "next", "ADJECTIVE", "A1", "ESSENTIALS", "Nächste Woche habe ich Zeit.", "Next week I have time.", None, None, None),
    # A2 stretch words for bank depth
    ("Erfahrung", "die", "Erfahrungen", "experience", "NOUN", "A2", "SCHOOL_WORK", "Ich habe wenig Erfahrung.", "I have little experience.", None, None, None),
    ("Entscheidung", "die", "Entscheidungen", "decision", "NOUN", "A2", "ESSENTIALS", "Das war eine schwere Entscheidung.", "That was a hard decision.", None, None, None),
    ("Möglichkeit", "die", "Möglichkeiten", "possibility", "NOUN", "A2", "ESSENTIALS", "Es gibt viele Möglichkeiten.", "There are many possibilities.", None, None, None),
    ("Problem", "das", "Probleme", "problem", "NOUN", "A1", "ESSENTIALS", "Das ist kein Problem.", "That is no problem.", None, None, None),
    ("Idee", "die", "Ideen", "idea", "NOUN", "A1", "ESSENTIALS", "Das ist eine gute Idee.", "That is a good idea.", None, None, None),
    ("Gefühl", "das", "Gefühle", "feeling", "NOUN", "A2", "PEOPLE", "Ich habe ein gutes Gefühl.", "I have a good feeling.", None, None, None),
    ("Meinung", "die", "Meinungen", "opinion", "NOUN", "A2", "ESSENTIALS", "Was ist deine Meinung?", "What is your opinion?", None, None, None),
    ("Grund", "der", "Gründe", "reason", "NOUN", "A2", "ESSENTIALS", "Aus diesem Grund bleibe ich.", "For this reason I am staying.", None, None, None),
    ("Beispiel", "das", "Beispiele", "example", "NOUN", "A1", "SCHOOL_WORK", "Zum Beispiel Berlin.", "For example Berlin.", None, None, None),
    ("Unterschied", "der", "Unterschiede", "difference", "NOUN", "A2", "SCHOOL_WORK", "Was ist der Unterschied?", "What is the difference?", None, None, None),
    ("Ergebnis", "das", "Ergebnisse", "result", "NOUN", "A2", "SCHOOL_WORK", "Das Ergebnis ist gut.", "The result is good.", None, None, None),
    ("Information", "die", "Informationen", "information", "NOUN", "A1", "ESSENTIALS", "Ich brauche mehr Informationen.", "I need more information.", None, None, None),
    ("Nachricht", "die", "Nachrichten", "message / news", "NOUN", "A1", "ESSENTIALS", "Ich habe eine Nachricht bekommen.", "I received a message.", None, None, None),
    ("Gespräch", "das", "Gespräche", "conversation", "NOUN", "A2", "PEOPLE", "Das Gespräch war lang.", "The conversation was long.", None, None, None),
    ("Termin", "der", "Termine", "appointment", "NOUN", "A1", "TIME", "Ich habe einen Termin um drei.", "I have an appointment at three.", None, None, None),
    ("Plan", "der", "Pläne", "plan", "NOUN", "A1", "ESSENTIALS", "Hast du einen Plan?", "Do you have a plan?", None, None, None),
    ("Ziel", "das", "Ziele", "goal / destination", "NOUN", "A2", "ESSENTIALS", "Mein Ziel ist B1.", "My goal is B1.", None, None, None),
    ("Chance", "die", "Chancen", "chance", "NOUN", "A2", "ESSENTIALS", "Das ist eine gute Chance.", "That is a good chance.", None, None, None),
    ("Angst", "die", "Ängste", "fear", "NOUN", "A2", "PEOPLE", "Ich habe Angst vor Prüfungen.", "I am afraid of exams.", None, None, "Angst haben vor + dative."),
    ("Hoffnung", "die", "Hoffnungen", "hope", "NOUN", "A2", "PEOPLE", "Es gibt noch Hoffnung.", "There is still hope.", None, None, None),
    ("erfolgreich", None, None, "successful", "ADJECTIVE", "A2", "DESCRIPTIONS", "Sie ist erfolgreich.", "She is successful.", None, None, None),
    ("wichtig", None, None, "important", "ADJECTIVE", "A1", "DESCRIPTIONS", "Das ist sehr wichtig.", "That is very important.", None, None, None),
    ("nötig", None, None, "necessary", "ADJECTIVE", "A2", "DESCRIPTIONS", "Das ist nicht nötig.", "That is not necessary.", None, None, None),
    ("einfach", None, None, "simple / easy", "ADJECTIVE", "A1", "DESCRIPTIONS", "Das ist ganz einfach.", "That is quite simple.", None, None, None),
    ("kompliziert", None, None, "complicated", "ADJECTIVE", "A2", "DESCRIPTIONS", "Die Regel ist kompliziert.", "The rule is complicated.", None, None, None),
    ("praktisch", None, None, "practical", "ADJECTIVE", "A2", "DESCRIPTIONS", "Das ist sehr praktisch.", "That is very practical.", None, None, None),
    ("modern", None, None, "modern", "ADJECTIVE", "A1", "DESCRIPTIONS", "Die Wohnung ist modern.", "The apartment is modern.", None, None, None),
    ("traditionell", None, None, "traditional", "ADJECTIVE", "A2", "DESCRIPTIONS", "Das Essen ist traditionell.", "The food is traditional.", None, None, None),
    ("entscheiden", None, None, "to decide", "VERB", "A2", "ESSENTIALS", "Ich muss mich entscheiden.", "I have to decide.", None, None, None),
    ("vergessen", None, None, "to forget", "VERB", "A1", "ESSENTIALS", "Vergiss das nicht!", "Don't forget that!", None, None, None),
    ("erinnern", None, None, "to remember", "VERB", "A2", "ESSENTIALS", "Ich erinnere mich an dich.", "I remember you.", None, None, "sich erinnern an."),
    ("versuchen", None, None, "to try", "VERB", "A1", "ESSENTIALS", "Ich versuche es noch einmal.", "I try it once more.", None, None, None),
    ("schaffen", None, None, "to manage / create", "VERB", "A2", "ESSENTIALS", "Du schaffst das!", "You can do it!", None, None, None),
    ("ändern", None, None, "to change", "VERB", "A2", "ESSENTIALS", "Ich möchte etwas ändern.", "I would like to change something.", None, None, None),
    ("verbessern", None, None, "to improve", "VERB", "A2", "SCHOOL_WORK", "Ich möchte mein Deutsch verbessern.", "I want to improve my German.", None, None, None),
    ("vorbereiten", None, None, "to prepare", "VERB", "A2", "SCHOOL_WORK", "Ich bereite die Prüfung vor.", "I prepare for the exam.", None, None, "Separable: vorbereiten."),
    ("wiederholen", None, None, "to repeat / review", "VERB", "A1", "SCHOOL_WORK", "Bitte wiederhole den Satz.", "Please repeat the sentence.", None, None, None),
    ("übersetzen", None, None, "to translate", "VERB", "A2", "SCHOOL_WORK", "Kannst du das übersetzen?", "Can you translate that?", None, None, None),
    ("verstehen", None, None, "to understand", "VERB", "A1", "SCHOOL_WORK", "Ich verstehe dich.", "I understand you.", None, None, None),
    ("meinen", None, None, "to mean / think", "VERB", "A1", "ESSENTIALS", "Was meinst du?", "What do you mean / think?", None, None, None),
    ("glauben", None, None, "to believe", "VERB", "A1", "ESSENTIALS", "Ich glaube dir.", "I believe you.", None, None, None),
    ("hoffen", None, None, "to hope", "VERB", "A1", "ESSENTIALS", "Ich hoffe auf gutes Wetter.", "I hope for good weather.", None, None, None),
    ("wünschen", None, None, "to wish", "VERB", "A1", "ESSENTIALS", "Ich wünsche dir viel Glück.", "I wish you good luck.", None, None, None),
    ("feiern", None, None, "to celebrate", "VERB", "A1", "PEOPLE", "Wir feiern Geburtstag.", "We celebrate a birthday.", None, None, None),
    ("lachen", None, None, "to laugh", "VERB", "A1", "PEOPLE", "Die Kinder lachen.", "The children laugh.", None, None, None),
    ("weinen", None, None, "to cry", "VERB", "A1", "PEOPLE", "Das Baby weint.", "The baby is crying.", None, None, None),
    ("schwimmen", None, None, "to swim", "VERB", "A1", "TRAVEL", "Im Sommer schwimme ich gern.", "In summer I like to swim.", None, None, None),
    ("laufen", None, None, "to run / walk", "VERB", "A1", "TRAVEL", "Ich laufe zum Bahnhof.", "I run/walk to the station.", None, None, None),
    ("wandern", None, None, "to hike", "VERB", "A2", "TRAVEL", "Am Wochenende wandern wir.", "On the weekend we hike.", None, None, None),
    ("tanzen", None, None, "to dance", "VERB", "A1", "PEOPLE", "Wir tanzen gern.", "We like to dance.", None, None, None),
    ("singen", None, None, "to sing", "VERB", "A1", "PEOPLE", "Sie singt schön.", "She sings beautifully.", None, None, None),
    ("malen", None, None, "to paint / draw", "VERB", "A1", "SCHOOL_WORK", "Die Kinder malen Bilder.", "The children paint pictures.", None, None, None),
    ("fotografieren", None, None, "to photograph", "VERB", "A2", "TRAVEL", "Darf ich fotografieren?", "May I take photos?", None, None, None),
    ("Geburtstag", "der", "Geburtstage", "birthday", "NOUN", "A1", "PEOPLE", "Wann hast du Geburtstag?", "When is your birthday?", None, None, None),
    ("Party", "die", "Partys", "party", "NOUN", "A1", "PEOPLE", "Die Party beginnt um acht.", "The party starts at eight.", None, None, None),
    ("Geschenk", "das", "Geschenke", "gift", "NOUN", "A1", "SHOPPING", "Ich kaufe ein Geschenk.", "I buy a gift.", None, None, None),
    ("Hobby", "das", "Hobbys", "hobby", "NOUN", "A1", "PEOPLE", "Mein Hobby ist Lesen.", "My hobby is reading.", None, None, None),
    ("Sport", "der", None, "sport", "NOUN", "A1", "PEOPLE", "Ich mache gerne Sport.", "I like doing sport.", None, None, None),
    ("Musik", "die", None, "music", "NOUN", "A1", "PEOPLE", "Ich höre gern Musik.", "I like listening to music.", None, None, None),
    ("Film", "der", "Filme", "film / movie", "NOUN", "A1", "PEOPLE", "Der Film war spannend.", "The film was exciting.", None, None, None),
    ("Foto", "das", "Fotos", "photo", "NOUN", "A1", "ESSENTIALS", "Mach bitte ein Foto.", "Please take a photo.", None, None, None),
    ("Zeitung", "die", "Zeitungen", "newspaper", "NOUN", "A1", "SCHOOL_WORK", "Ich lese die Zeitung.", "I read the newspaper.", None, None, None),
    ("Brief", "der", "Briefe", "letter", "NOUN", "A1", "SCHOOL_WORK", "Ich schreibe einen Brief.", "I write a letter.", None, None, None),
    ("Adresse", "die", "Adressen", "address", "NOUN", "A1", "ESSENTIALS", "Wie ist deine Adresse?", "What is your address?", None, None, None),
    ("Telefonnummer", "die", "Telefonnummern", "phone number", "NOUN", "A1", "ESSENTIALS", "Wie ist deine Telefonnummer?", "What is your phone number?", None, None, None),
    ("Internet", "das", None, "internet", "NOUN", "A1", "SCHOOL_WORK", "Das Internet ist langsam.", "The internet is slow.", None, None, None),
    ("Website", "die", "Websites", "website", "NOUN", "A1", "SCHOOL_WORK", "Die Website ist neu.", "The website is new.", None, None, None),
    ("Passwort", "das", "Passwörter", "password", "NOUN", "A2", "SCHOOL_WORK", "Vergiss dein Passwort nicht.", "Don't forget your password.", None, None, None),
    ("Konto", "das", "Konten", "account", "NOUN", "A2", "SHOPPING", "Ich eröffne ein Konto.", "I open an account.", None, None, None),
    ("Kreditkarte", "die", "Kreditkarten", "credit card", "NOUN", "A1", "SHOPPING", "Kann ich mit Kreditkarte zahlen?", "Can I pay by credit card?", None, None, None),
    ("bar", None, None, "in cash", "ADVERB", "A1", "SHOPPING", "Ich zahle bar.", "I pay cash.", None, None, None),
    ("online", None, None, "online", "ADVERB", "A1", "SHOPPING", "Ich kaufe online.", "I shop online.", None, None, None),
    ("vielleicht", None, None, "maybe", "ADVERB", "A1", "ESSENTIALS", "Vielleicht komme ich später.", "Maybe I'll come later.", None, None, None),
    ("natürlich", None, None, "of course / natural", "ADVERB", "A1", "ESSENTIALS", "Natürlich helfe ich dir.", "Of course I'll help you.", None, None, None),
    ("eigentlich", None, None, "actually", "ADVERB", "A2", "ESSENTIALS", "Eigentlich habe ich keine Zeit.", "Actually I don't have time.", None, None, None),
    ("wirklich", None, None, "really", "ADVERB", "A1", "ESSENTIALS", "Ist das wirklich wahr?", "Is that really true?", None, None, None),
    ("genau", None, None, "exactly", "ADVERB", "A1", "ESSENTIALS", "Genau das meine ich.", "Exactly that is what I mean.", None, None, None),
    ("ungefähr", None, None, "approximately", "ADVERB", "A1", "ESSENTIALS", "Es dauert ungefähr eine Stunde.", "It takes about an hour.", None, None, None),
    ("genug", None, None, "enough", "ADVERB", "A1", "ESSENTIALS", "Ich habe genug Geld.", "I have enough money.", None, None, None),
    ("mehr", None, None, "more", "ADVERB", "A1", "ESSENTIALS", "Ich möchte mehr lernen.", "I want to learn more.", None, None, None),
    ("weniger", None, None, "less / fewer", "ADVERB", "A1", "ESSENTIALS", "Weniger Zucker, bitte.", "Less sugar, please.", None, None, None),
    ("beide", None, None, "both", "PRONOUN", "A1", "ESSENTIALS", "Beide kommen mit.", "Both are coming along.", None, None, None),
    ("andere", None, None, "other", "ADJECTIVE", "A1", "ESSENTIALS", "Hast du eine andere Idee?", "Do you have another idea?", None, None, None),
    ("gleiche", None, None, "same", "ADJECTIVE", "A1", "ESSENTIALS", "Wir haben die gleiche Meinung.", "We have the same opinion.", None, None, None),
    ("eigene", None, None, "own", "ADJECTIVE", "A1", "ESSENTIALS", "Ich habe meine eigene Wohnung.", "I have my own apartment.", None, None, None),
    ("zusammen", None, None, "together", "ADVERB", "A1", "ESSENTIALS", "Wir lernen zusammen.", "We learn together.", None, None, None),
    ("zurück", None, None, "back", "ADVERB", "A1", "TRAVEL", "Wann kommst du zurück?", "When are you coming back?", None, None, None),
    ("weg", None, None, "away / gone", "ADVERB", "A1", "TRAVEL", "Er ist schon weg.", "He is already gone.", None, None, None),
    ("drin", None, None, "inside", "ADVERB", "A1", "HOME", "Ist jemand drin?", "Is someone inside?", None, None, None),
    ("draußen", None, None, "outside", "ADVERB", "A1", "HOME", "Die Kinder spielen draußen.", "The children play outside.", None, None, None),
    ("oben", None, None, "upstairs / above", "ADVERB", "A1", "HOME", "Das Bad ist oben.", "The bathroom is upstairs.", None, None, None),
    ("unten", None, None, "downstairs / below", "ADVERB", "A1", "HOME", "Die Küche ist unten.", "The kitchen is downstairs.", None, None, None),
    ("drinbleiben", None, None, "to stay inside", "VERB", "A2", "HOME", "Bei Regen bleiben wir drin.", "When it rains we stay inside.", None, None, None),
    ("mitkommen", None, None, "to come along", "VERB", "A1", "PEOPLE", "Kommst du mit?", "Are you coming along?", None, None, "Separable: mitkommen."),
    ("mitbringen", None, None, "to bring along", "VERB", "A1", "ESSENTIALS", "Bring bitte Brot mit.", "Please bring bread along.", None, None, "Separable: mitbringen."),
    ("aufmachen", None, None, "to open", "VERB", "A1", "HOME", "Mach das Fenster auf!", "Open the window!", None, None, "Separable colloquial."),
    ("zumachen", None, None, "to close", "VERB", "A1", "HOME", "Mach die Tür zu!", "Close the door!", None, None, "Separable colloquial."),
    ("aufräumen", None, None, "to tidy up", "VERB", "A1", "HOME", "Bitte räum dein Zimmer auf.", "Please tidy your room.", None, None, "Separable: aufräumen."),
    ("abwaschen", None, None, "to wash up (dishes)", "VERB", "A1", "HOME", "Ich wasche ab.", "I wash the dishes.", None, None, "Separable: abwaschen."),
    ("einkaufen gehen", None, None, "to go shopping", "VERB", "A1", "SHOPPING", "Wir gehen nachher einkaufen.", "We go shopping later.", None, None, None),
    ("Bescheid", "der", None, "notice / word (Bescheid geben)", "NOUN", "A2", "ESSENTIALS", "Gib mir bitte Bescheid.", "Please let me know.", None, None, "Common: Bescheid geben."),
    ("Glück", "das", None, "luck / happiness", "NOUN", "A1", "ESSENTIALS", "Viel Glück!", "Good luck!", None, None, None),
    ("Spaß", "der", None, "fun", "NOUN", "A1", "PEOPLE", "Das macht Spaß.", "That is fun.", None, None, None),
    ("Ruhe", "die", None, "quiet / rest", "NOUN", "A1", "ESSENTIALS", "Ich brauche Ruhe.", "I need quiet / rest.", None, None, None),
    ("Hilfe", "die", None, "help", "NOUN", "A1", "ESSENTIALS", "Hilfe!", "Help!", None, None, None),
    ("Vorsicht", "die", None, "caution", "NOUN", "A1", "ESSENTIALS", "Vorsicht, Stufe!", "Caution, step!", None, None, None),
    ("Achtung", "die", None, "attention / warning", "NOUN", "A1", "ESSENTIALS", "Achtung, bitte!", "Attention, please!", None, None, None),
    ("Willkommen", "das", None, "welcome", "NOUN", "A1", "ESSENTIALS", "Herzlich willkommen!", "A warm welcome!", None, None, None),
    ("Tschüss", None, None, "bye", "OTHER", "A1", "ESSENTIALS", "Tschüss und bis bald!", "Bye and see you soon!", None, None, None),
    ("Hallo", None, None, "hello", "OTHER", "A1", "ESSENTIALS", "Hallo, wie geht's?", "Hello, how are you?", None, None, None),
    ("Guten Tag", None, None, "good day / hello", "OTHER", "A1", "ESSENTIALS", "Guten Tag, Frau Müller.", "Good day, Ms Müller.", None, None, None),
    ("Guten Morgen", None, None, "good morning", "OTHER", "A1", "ESSENTIALS", "Guten Morgen allerseits!", "Good morning everyone!", None, None, None),
    ("Gute Nacht", None, None, "good night", "OTHER", "A1", "ESSENTIALS", "Gute Nacht und schlaf gut.", "Good night and sleep well.", None, None, None),
    ("Entschuldigung", "die", "Entschuldigungen", "excuse me / apology", "NOUN", "A1", "ESSENTIALS", "Entschuldigung, wo ist der Bahnhof?", "Excuse me, where is the station?", None, None, None),
    ("Bitte schön", None, None, "you're welcome / here you are", "OTHER", "A1", "ESSENTIALS", "Bitte schön!", "Here you are / you're welcome!", None, None, None),
    ("Gern geschehen", None, None, "you're welcome", "OTHER", "A1", "ESSENTIALS", "Gern geschehen!", "You're welcome!", None, None, None),
    ("Prost", None, None, "cheers", "OTHER", "A1", "FOOD_DRINK", "Prost!", "Cheers!", None, None, None),
    ("Mahlzeit", "die", "Mahlzeiten", "meal / enjoyable meal greeting", "NOUN", "A1", "FOOD_DRINK", "Mahlzeit!", "Enjoy your meal! (greeting)", None, None, None),
    ("Hunger haben", None, None, "to be hungry", "VERB", "A1", "FOOD_DRINK", "Hast du Hunger?", "Are you hungry?", None, None, None),
    ("Durst haben", None, None, "to be thirsty", "VERB", "A1", "FOOD_DRINK", "Ich habe Durst.", "I am thirsty.", None, None, None),
    ("Lust", "die", None, "desire / mood for", "NOUN", "A1", "ESSENTIALS", "Hast du Lust auf Kaffee?", "Do you feel like coffee?", None, None, "Lust haben auf."),
    ("Recht", "das", "Rechte", "right (law / entitlement)", "NOUN", "A2", "ESSENTIALS", "Du hast Recht.", "You are right.", None, None, "Recht haben = to be right."),
    ("Unrecht", "das", None, "wrong (to be wrong)", "NOUN", "A2", "ESSENTIALS", "Ich habe Unrecht.", "I am wrong.", None, None, None),
    ("Wahrheit", "die", "Wahrheiten", "truth", "NOUN", "A2", "ESSENTIALS", "Das ist die Wahrheit.", "That is the truth.", None, None, None),
    ("Lüge", "die", "Lügen", "lie", "NOUN", "A2", "ESSENTIALS", "Das ist eine Lüge.", "That is a lie.", None, None, None),
    ("Sicherheit", "die", None, "safety / security", "NOUN", "A2", "ESSENTIALS", "Sicherheit ist wichtig.", "Safety is important.", None, None, None),
    ("Gefahr", "die", "Gefahren", "danger", "NOUN", "A2", "ESSENTIALS", "Vorsicht, Gefahr!", "Caution, danger!", None, None, None),
    ("sicher", None, None, "safe / sure", "ADJECTIVE", "A1", "DESCRIPTIONS", "Bist du sicher?", "Are you sure?", None, None, None),
    ("gefährlich", None, None, "dangerous", "ADJECTIVE", "A1", "DESCRIPTIONS", "Das ist gefährlich.", "That is dangerous.", None, None, None),
    ("vorsichtig", None, None, "careful", "ADJECTIVE", "A1", "DESCRIPTIONS", "Sei bitte vorsichtig.", "Please be careful.", None, None, None),
    ("plötzlich", None, None, "suddenly", "ADVERB", "A2", "TIME", "Plötzlich regnete es.", "Suddenly it rained.", None, None, None),
    ("sofort", None, None, "immediately", "ADVERB", "A1", "TIME", "Komm sofort!", "Come immediately!", None, None, None),
    ("endlich", None, None, "finally", "ADVERB", "A1", "TIME", "Endlich Feierabend!", "Finally quitting time!", None, None, None),
    ("zuerst", None, None, "first (of all)", "ADVERB", "A1", "TIME", "Zuerst waschen wir die Hände.", "First we wash our hands.", None, None, None),
    ("dann", None, None, "then", "ADVERB", "A1", "TIME", "Dann gehen wir essen.", "Then we go eat.", None, None, None),
    ("danach", None, None, "after that", "ADVERB", "A1", "TIME", "Danach machen wir Pause.", "After that we take a break.", None, None, None),
    ("vorher", None, None, "beforehand", "ADVERB", "A1", "TIME", "Ruf vorher an.", "Call beforehand.", None, None, None),
    ("seit", None, None, "since / for (time)", "PREPOSITION", "A1", "TIME", "Ich lerne seit einem Jahr Deutsch.", "I have been learning German for a year.", None, None, "Takes dative."),
    ("bis", None, None, "until / to", "PREPOSITION", "A1", "TIME", "Bis morgen!", "See you tomorrow!", None, None, None),
    ("während", None, None, "during / while", "PREPOSITION", "A2", "TIME", "Während der Pause trinke ich Tee.", "During the break I drink tea.", None, None, None),
    ("obwohl", None, None, "although", "CONJUNCTION", "A2", "ESSENTIALS", "Obwohl es regnet, gehe ich raus.", "Although it rains, I go out.", None, None, None),
    ("weil", None, None, "because", "CONJUNCTION", "A1", "ESSENTIALS", "Ich bleibe, weil ich müde bin.", "I stay because I am tired.", None, None, "Verb to end."),
    ("dass", None, None, "that (conjunction)", "CONJUNCTION", "A1", "ESSENTIALS", "Ich glaube, dass das stimmt.", "I believe that that is true.", None, None, None),
    ("wenn", None, None, "if / when", "CONJUNCTION", "A1", "ESSENTIALS", "Wenn ich Zeit habe, komme ich.", "If/when I have time, I'll come.", None, None, None),
    ("als", None, None, "when (past) / as", "CONJUNCTION", "A1", "ESSENTIALS", "Als ich jung war, wohnte ich dort.", "When I was young, I lived there.", None, None, None),
    ("ob", None, None, "whether / if", "CONJUNCTION", "A1", "ESSENTIALS", "Ich weiß nicht, ob er kommt.", "I don't know whether he is coming.", None, None, None),
    ("denn", None, None, "because / for", "CONJUNCTION", "A1", "ESSENTIALS", "Ich gehe, denn ich bin müde.", "I am going, because I am tired.", None, None, "Does not kick verb to end."),
    ("aber", None, None, "but", "CONJUNCTION", "A1", "ESSENTIALS", "Ich will, aber ich kann nicht.", "I want to, but I can't.", None, None, None),
    ("sondern", None, None, "but rather", "CONJUNCTION", "A2", "ESSENTIALS", "Nicht heute, sondern morgen.", "Not today, but rather tomorrow.", None, None, "After negation."),
    ("entweder", None, None, "either", "CONJUNCTION", "A2", "ESSENTIALS", "Entweder Tee oder Kaffee.", "Either tea or coffee.", None, None, "entweder … oder."),
    ("sowohl", None, None, "both … and", "CONJUNCTION", "A2", "ESSENTIALS", "Sowohl Anna als auch Tom kommen.", "Both Anna and Tom are coming.", None, None, "sowohl … als auch."),
]

# Known-good Commons images for concrete nouns (credit verified from Commons file pages / existing bank style).
IMAGES: dict[str, dict[str, str]] = {
    "Käse": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Cheese_platter.jpg/960px-Cheese_platter.jpg",
        "credit": "Jon Sullivan",
        "license": "Public domain",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cheese_platter.jpg",
    },
    "Ei": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Egg_and_toast.jpg/960px-Egg_and_toast.jpg",
        "credit": "Renee Comet (NCI)",
        "license": "Public domain",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Egg_and_toast.jpg",
    },
    "Banane": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Banana-Single.jpg/960px-Banana-Single.jpg",
        "credit": "AugiasSTA",
        "license": "CC0",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Banana-Single.jpg",
    },
    "Tomate": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/960px-Tomato_je.jpg",
        "credit": "User:J.E.",
        "license": "CC BY-SA 3.0",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tomato_je.jpg",
    },
    "Fahrrad": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Left_side_of_Flying_Pigeon.jpg/960px-Left_side_of_Flying_Pigeon.jpg",
        "credit": "User:Flying Pigeon",
        "license": "CC BY-SA 3.0",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Left_side_of_Flying_Pigeon.jpg",
    },
    "Hotel": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Hotel_bed.jpg/960px-Hotel_bed.jpg",
        "credit": "User:Jebulon",
        "license": "CC0",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hotel_bed.jpg",
    },
    "Sofa": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Sofa_bed.jpg/960px-Sofa_bed.jpg",
        "credit": "User:Interiot",
        "license": "Public domain",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sofa_bed.jpg",
    },
    "Lampe": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Table_lamp.jpg/960px-Table_lamp.jpg",
        "credit": "User:David.Monniaux",
        "license": "CC BY-SA 3.0",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Table_lamp.jpg",
    },
    "Schuh": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Leather_shoes.jpg/960px-Leather_shoes.jpg",
        "credit": "User:David.Monniaux",
        "license": "CC BY-SA 1.0",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Leather_shoes.jpg",
    },
    "Park": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Central_Park_New_York_City_New_York_23.jpg/960px-Central_Park_New_York_City_New_York_23.jpg",
        "credit": "User:Daderot",
        "license": "CC0",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Central_Park_New_York_City_New_York_23.jpg",
    },
    "Brücke": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Brooklyn_Bridge_Postdlf.jpg/960px-Brooklyn_Bridge_Postdlf.jpg",
        "credit": "User:Postdlf",
        "license": "CC BY-SA 3.0",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Brooklyn_Bridge_Postdlf.jpg",
    },
    "Berg": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg/960px-Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg",
        "credit": "Luca Galuzzi",
        "license": "CC BY-SA 2.5",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Everest_North_Face_toward_Base_Camp_Tibet_Luca_Galuzzi_2006.jpg",
    },
    "Sonne": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg/960px-The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg",
        "credit": "NASA/SDO",
        "license": "Public domain",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:The_Sun_by_the_Atmospheric_Imaging_Assembly_of_NASA%27s_Solar_Dynamics_Observatory_-_20100819.jpg",
    },
    "Supermarkt": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Grocery_store_aisle.jpg/960px-Grocery_store_aisle.jpg",
        "credit": "User:Mike Mozart",
        "license": "CC BY 2.0",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Grocery_store_aisle.jpg",
    },
    "Glas": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Glass-of-water.jpg/960px-Glass-of-water.jpg",
        "credit": "User:Fir0002",
        "license": "CC BY 2.5",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Glass-of-water.jpg",
    },
    "Tasse": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/A_small_cup_of_coffee.JPG/960px-A_small_cup_of_coffee.JPG",
        "credit": "User:Julius Schorzman",
        "license": "CC BY-SA 2.0",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_small_cup_of_coffee.JPG",
    },
    "Koffer": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Suitcase.jpg/960px-Suitcase.jpg",
        "credit": "User:Evan-Amos",
        "license": "Public domain",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Suitcase.jpg",
    },
    "Schlüssel": {
        "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Key.agr.jpg/960px-Key.agr.jpg",
        "credit": "User:ArnoldReinhold",
        "license": "CC BY-SA 3.0",
        "sourceUrl": "https://commons.wikimedia.org/wiki/File:Key.agr.jpg",
    },
}


def row_to_word(row: tuple, rank: int) -> dict:
    lemma, article, plural, translation, pos, cefr, topic, ex_de, ex_en, ex_pl_de, ex_pl_en, note = row
    word = {
        "lemma": lemma,
        "article": article,
        "plural": plural,
        "translation": translation,
        "partOfSpeech": pos,
        "cefrBand": cefr,
        "topic": topic,
        "exampleDe": ex_de,
        "exampleEn": ex_en,
        "usageNote": note,
        "frequencyRank": rank,
    }
    if ex_pl_de:
        word["examplePluralDe"] = ex_pl_de
        word["examplePluralEn"] = ex_pl_en
    if lemma in IMAGES and article:  # concrete nouns with article
        word["image"] = IMAGES[lemma]
    return word


def main() -> None:
    # Fix known issues in RAW before merge
    cleaned: list[tuple] = []
    seen_local: set[tuple[str, str]] = set()
    for row in RAW + MORE:
        lemma = row[0]
        article = row[1] or ""
        key = (lemma, article)
        # Skip known bad / duplicate entries
        if lemma == "probieren" and "proberen" in row[7]:
            row = (
                "probieren",
                None,
                None,
                "to try / try on",
                "VERB",
                "A1",
                "SHOPPING",
                "Kann ich das anprobieren?",
                "Can I try that on?",
                None,
                None,
                None,
            )
            key = ("probieren", "")
        if lemma == "Badzimmer":
            # Prefer das Bad already in bank; use Badezimmer instead
            row = (
                "Badezimmer",
                "das",
                "Badezimmer",
                "bathroom",
                "NOUN",
                "A1",
                "HOME",
                "Das Badezimmer ist frei.",
                "The bathroom is free.",
                None,
                None,
                None,
            )
            key = ("Badezimmer", "das")
        if key in EXISTING or key in seen_local:
            continue
        # Skip second öffnen (already in HOME list) when it appears in shopping with A2
        if lemma == "öffnen" and key in seen_local:
            continue
        seen_local.add(key)
        cleaned.append(row)

    # Remove duplicate öffnen if both present - keep first
    final: list[tuple] = []
    seen2: set[tuple[str, str]] = set()
    for row in cleaned:
        key = (row[0], row[1] or "")
        if key in seen2:
            continue
        # öffnen appears twice intentionally avoided
        if key in EXISTING:
            continue
        # Skip ohne/mit if already in batch-01
        seen2.add(key)
        final.append(row)

    # Also drop entries that duplicate EXISTING lemmas with same article
    final = [r for r in final if (r[0], r[1] or "") not in EXISTING]

    # Drop ohne and mit if already in existing (they are)
    start_rank = 110
    words = [row_to_word(row, start_rank + i) for i, row in enumerate(final)]

    # Ensure we have at least 391 new words to reach 500
    if len(words) < 391:
        raise SystemExit(f"Need at least 391 new words, got {len(words)}")

    # Trim to nice total if overshoot massively - keep all if reasonable
    # Write in batches of ~100
    batch_size = 100
    for i in range(0, len(words), batch_size):
        chunk = words[i : i + batch_size]
        n = 2 + i // batch_size
        path = OUT / f"a1-batch-{n:02d}.json"
        path.write_text(json.dumps(chunk, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {len(chunk)} words -> {path}")

    total = 109 + len(words)
    print(f"New words: {len(words)}; grand total with batch-01: {total}")


if __name__ == "__main__":
    main()
